### PR TITLE
Upgrade to Django4

### PR DESCRIPTION
**Pull request by dchiller**

### CODE REVIEW

**Comment by napulen** [comment]
@dchiller did this configuration result in a working set of containers?

**Comment by dchiller** [comment]
Yes! Everything is working -- the only thing I encountered was the "Session data corrupted" error, but since Eli found that in the 3.2 version too, I think it is a separate issue.

**Comment by napulen** [comment]
Awesome! So we can leave the `django4` branch lying there. Today, I noticed that the Alpha for `django==4.1.0` is out, so we could technically be early adopters of 4.1 and then we have full support until 4.2 comes out.

Not sure that it's worth it, because it is an "alpha" after all.

**Comment by napulen** [comment]
So I'm still in favor of leaving this one here for keeping this conversation alive by the time `4.2` is out.

**Comment by dchiller** [comment]
Closing....solved with #744

**Pull request closed without merging**
