### PR TITLE
fix hanging on man-db tasks when building on windows

### PR DESCRIPTION
**Pull request by eliwaksbaum**
fix for #396, remove man-db package in provision

### CODE REVIEW

**Comment by eliwaksbaum** [comment]
small regex fix stops static pages from crashing on windows

**Review by napulen — CHANGES_REQUESTED** [review]
The fix for the provisioning looks great!

Regarding the url regex, I am concerned that leaving an open-ended string (no `$` check) would potentially open this code to security vulnerabilities (people adding extra characters at the url and passing the validation). I understand that this is a problem related to the Windows CRLF syntax (`\n\r`)?

How about we do an optional return carriage symbol before the end of line `$`? That'd probably work for *nix/Windows while not allowing arbitrary urls.

**Comment by napulen** [comment]
I think something like this would work? (Did not test)

```
r"^#([A-Za-z0-9 _-]+)\r?$
```

Can you try moving in this direction for this fix, @eliwaksbaum?

**Review by napulen — APPROVED** [review]
Nice!

**Pull request merged**
