### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by napulen**
A rebased version of @eliwaksbaum's #423

fixes https://github.com/DDMAL/cantus/issues/415
fixes https://github.com/DDMAL/cantus/issues/394
fixes https://github.com/DDMAL/cantus/issues/417
fixes https://github.com/DDMAL/cantus/issues/429
fixes https://github.com/DDMAL/cantus/issues/433
fixes https://github.com/DDMAL/cantus/issues/424

### CODE REVIEW

**Comment by napulen** [comment]
@dchiller can you try running this version locally? pretty big PR

**Comment by napulen** [comment]
Not concerned about unit tests not passing here. We can patch them in subsequent PRs.

**Review by eliwaksbaum — APPROVED** [review]

**Comment by dchiller** [comment]
@napulen @eliwaksbaum Just to confirm: I am just building and running the containers here as normal -- the tests part happens with github actions, so I don't need to run any other commands, etc for that?

**Comment by dchiller** [comment]
I approved -- the site worked for me and everything, but I have a question about the tests themselves...

**Comment by napulen** [comment]
> @napulen @eliwaksbaum Just to confirm: I am just building and running the containers here as normal -- the tests part happens with github actions, so I don't need to run any other commands, etc for that?

Correct. You can run them manually too, but the automation happens on github (actions).

**Comment by napulen** [comment]
> I approved -- the site worked for me and everything, but I have a question about the tests themselves...

Go ahead! Or was it the previous question about gh actions?

**Comment by dchiller** [comment]
The question was about specific tests...I think @eliwaksbaum said that they were already written and he just implemented them?

**Comment by eliwaksbaum** [comment]
Yeah they've been sitting in the repo for a while

**Comment by napulen** [comment]
Cool, so I think we can merge as-is

**Pull request merged**
