### PR TITLE
Readme

### LINKED ISSUE #446: Update documentation for docker version
The current documentation accounts for a development/production workflow based on `Vagrant`.

It needs to be replaced to account for how things work now with `docker`.

### PR DESCRIPTION
**Pull request by eliwaksbaum**
fixes #446

### CODE REVIEW

**Review by napulen — APPROVED** [review]
This is great! Thank you @eliwaksbaum. I added some changes.

**Comment by napulen** [comment]
I'll re-read before merging it.

**Comment by dchiller** [comment]
What's the change to the nginx part of docker-compose.yaml?

**Review by dchiller — APPROVED** [review]
Love the readme!

**Comment by napulen** [comment]
> Maybe one thing to add to the read-me is about that error where (if you are developing) you need to make sure the folders where the postgres db is persisted are deleted -- or else upon rebuild postgres will not initialize....

Yes, that's important

**Comment by eliwaksbaum** [comment]
> Maybe one thing to add to the read-me is about that error where (if you are developing) you need to make sure the folders where the postgres db is persisted are deleted -- or else upon rebuild postgres will not initialize....

That happens when you change the password, right?

**Comment by napulen** [comment]
> > Maybe one thing to add to the read-me is about that error where (if you are developing) you need to make sure the folders where the postgres db is persisted are deleted -- or else upon rebuild postgres will not initialize....
> 
> That happens when you change the password, right?

Yeah, I think the particular case I ran into was
- I forgot to set up the password on `.env` and launched the container
- Realized that I didn't set up a password, so I edited `.env`
- I re-built the containers and ran into this `postgres` issue

**Comment by napulen** [comment]
I pushed a rough draft of the `postgres` issue

**Comment by napulen** [comment]
I also re-read the complete `README` file and I am good to go.

Can you review/double-check/edit the `postgres` section? After that, I think we are good to go with this documentation 👍

**Comment by eliwaksbaum** [comment]
Is removing the volume with the docker cli enough or do you have to actually delete the files on your machine?

**Comment by napulen** [comment]
> Is removing the volume with the docker cli enough or do you have to actually delete the files on your machine?

I don't know for sure, but I can just add the `rm` instruction to the readme.

**Comment by dchiller** [comment]
I have always just removed the files, independent of docker, but if removing the volume does the trick, looks great!

**Comment by napulen** [comment]
The problem I had removing just the files is that I run into a weird `permission denied` issue, probably because something on the docker daemon is holding that folder.

**Comment by napulen** [comment]
Ok, merging the current docs. Corrections can come in future PRs as usual.

**Pull request merged**
