### PR TITLE
library speed tests

### LINKED ISSUE #394: Measure the networking speed of source libraries
If the upload speed(?) of a digital library is not very good, that results in Cantus Ultimus taking a long time to load images. Furthermore, it is beyond our control to make the user experience smoother in that case.

I have seen that happening in the past, but I haven't quantified those kinds of problems, or how often they'd occur and where.

We could run some tests on this to find out which IIIF manifests tend to take a long time to be served and where they are coming from.

### PR DESCRIPTION
**Pull request by eliwaksbaum**
Fixes #394

### CODE REVIEW

**Review by napulen — CHANGES_REQUESTED** [review]
All good! Just waiting for the new tests based on Andrew's feedback.

**Comment by napulen** [comment]
For some reason, the Github automation doesn't automatically close an issue on merge unless you explicitly write a word like `Fixe[d|s] #0000`. Please always include such a verbal cue before the issue number.

**Comment by eliwaksbaum** [comment]
I'm discovering all sorts of interesting things about requesting IIIF images and these tests are not up to snuff. I'll reopen once I figure out what exactly we want to do here. For example, one issue that comes up is the transformations not working since something in the uri isn't right, so we just get the same thumbnail over and over. Some test in here should be looking for that. There's more to knowing if a manifest will work with our system than whether we get a 200 response back

**Comment by napulen** [comment]
This is starting to sound like we need a IIIF module in the codebase, for parsing, error-handling, testing, etc.

**Pull request closed without merging**
